### ISSUE TITLE
Tile clipping results in edge artifacts

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#100]
This can be seen in the following image:

![clipping_480](https://cloud.githubusercontent.com/assets/667850/23584400/6a5aa0e6-0115-11e7-97ed-e85393a7d421.png)

And can be addressed with a configurable tile buffer which allows geometries to extend beyond the extent of the tile. This is discussed in [MVT Specification, Section 4.1. Layers](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#41-layers):

> A layer MUST contain an extent that describes the width and height of the tile in integer coordinates. The geometries within the Vector Tile MAY extend past the bounds of the tile's area as defined by the extent. Geometries that extend past the tile's area as defined by extent are often used as a buffer for rendering features that overlap multiple adjacent tiles.

This technique is a "hack" per the discussion on the MVT Specification repo [here](https://github.com/mapbox/vector-tile-spec/issues/26#issuecomment-63902337).

**Comment by gdey** [comment]
Closing as these are issues are related to clipping #56.
