### ISSUE TITLE
Support text ids (not just int64)

### ISSUE THREAD

**Issue by kachkaev** [terranodo/tegola#101]
Hi guys,

I've got a few experimental postgis tables that I'd like to expose via tegola and I've got an issue with type of the id field. In my case it is text, because I don't care much about the performance and in fact believe that it's not that different these days. As a result, the tile server logs show the following:

```
Error Getting MVTLayer: Unable to convert geometry ID field(id) into a uint64 for layer my_map
```

What would you suggest as a workaround? What do you think of supporting character ids as well?

__PS:__ Perhaps this "lazy ass" scenario which I'm representing is not the only one when character ids might be needed. I can easily imagine a data provider where object ids are like `NW:121212:121212`, `d131dd02c5e6eec4693d9a0698aff95c` or similar. ATM developers would have to create another artificial id column next to the given proper id to work with tegola. So do I now as my ids are text already.

**Comment by kachkaev** [comment]
Tried `id_fieldname = "md5(id)::unit64 as id"` but it did not work. Tegola wrapped this into `""`, so I got this:

```
Error Getting MVTLayer: Got the following error (ERROR: column "md5(id)::unit64 as id" does not exist (SQLSTATE 42703)) running this sql (SELECT ... , ST_AsBinary("my_geom") AS "my_geom", "md5(id)::unit64 as id" FROM ...
```

**Comment by kachkaev** [comment]
Finally got this working:

```toml
    [[providers.layers]]
    name = "my_layer"
    geometry_fieldname = "my_geom"
    id_fieldname = "tegola_id"
    srid = 4326
    sql = """
      SELECT
        ('x'||substr(md5(id),1,16))::bit(64)::bigint as tegola_id,
        ST_AsBinary(my_geom) AS my_geom,
        other_field_1, other_field_2
      FROM my_table
      WHERE my_geom && !BBOX!
      """
```

The idea for getting a numeric key from a string is [from StackOverflow](http://stackoverflow.com/a/9812029/1818285). Although the workaround allows to achieve the result, it'd be still better to have text ids natively (if there are no serious consequences for this, of course).

**Comment by ARolek** [comment]
@kachkaev seems like a reasonable request. I think we can add support [here](https://github.com/terranodo/tegola/blob/master/provider/postgis/postgis.go#L419). I will try to address it in our v0.4.0 branch so it will be part of an upcoming release.

**Comment by kachkaev** [comment]
Awesome! Glad that the current internal architecture allows for a potentially easy fix!

It'd be great if you considered docker integration as well - the [current image available on Docker Hub](https://hub.docker.com/r/terranodo/tegola/) is not official and is actually two forks [away](https://github.com/ingenieroariel/tegola). I've been using tegola inside a Docker container bundled with my custom config and it has been so convenient to carry this stuff around between the servers!

**Comment by jj0hns0n** [comment]
sorry to hijack this issue, but @timlinux has a working docker setup. Tim, can you send a PR?

**Comment by ARolek** [comment]
@kachkaev we did some research on why we were specifically requiring int64 for feature ids and it's because the protocol buffer definition provided alongside the MVT spec requires uint64 for feature id. I opened an issue on the spec repo [here](https://github.com/mapbox/vector-tile-spec/issues/94#issuecomment-294591646) and got a response from one of the spec authors. it looks like best practice right now is to encode text ids into a tag (i.e. feature_id) which support text types. 

Let me know if this is unclear or if you need help with the config file. We may need to relax our requirements for Feature IDs since it's not required.
