### ISSUE TITLE
Static endpoint is not working on Windows 10

### ISSUE THREAD

**Issue by donnyv** [terranodo/tegola#117]
I tried using the static endpoint to test a sample and it kept responding with a 404. I looked at the GO code and it looks like you're missing a "/'' at the beginning of "static".

reference: http://stackoverflow.com/questions/28793619/golang-what-to-use-http-servefile-or-http-fileserver

**Comment by ARolek** [comment]
@donnyv thanks for this report as well. I will work on a fix and let you know when it's up.

**Comment by ARolek** [comment]
@donnyv I'm having trouble recreating this issue. Was your `static` folder next to your tegola binary? tegola will look for a folder called `static` that is next to it for file serving.

**Comment by donnyv** [comment]
Yes

**Comment by ARolek** [comment]
tegola no longer has a static webserver endpoint. This may be re-introduce later if there is enough demand. For now, the built in viewer at project root will render an autogenerated style of the map form the configured data provider(s)
