### ISSUE TITLE
Outdated release links

### ISSUE THREAD

**Issue by pnorman** [terranodo/tegola#124]
http://tegola.io/getting-started/#1-download-tegola gives links to https://github.com/terranodo/tegola/releases/download/v0.2.0/tegola_linux_amd64, which is v0.2.0, not the latest released v0.3.2

**Comment by ARolek** [comment]
@pnorman thanks for the report! I just pushed up a quick fix. If you notice any other documentation issues, feel free to file an issue on our [tegola-docs](https://github.com/terranodo/tegola-docs) repo.
