### ISSUE TITLE
Support for PORT environment variable

### ISSUE THREAD

**Issue by mojodna** [terranodo/tegola#133]
In some contexts, `PORT` is provided in the environment as an alternative to specifying it on the command line. It would be nice if tegola respected this, with preferences in this order:

1. config file
2. `PORT`
3. command line

**Comment by mojodna** [comment]
(Changed to `PORT`; I don't know what I was previously thinking.)

**Comment by ARolek** [comment]
The port can be set in several ways now:

- config file, hard coded
- config file, via environment vars (i.e. $PORT)
- command line via `tegola serve --config tegola.toml --port = ":9090"
