### ISSUE TITLE
Redo logging output.

### ISSUE THREAD

**Issue by sacontreras** [terranodo/tegola#147]
1. tegola - at least in 0.4.0 branch - seems to send output meant for stdout to stderr - e.g. loading config notification and successful server start messages are output to stderr, not stdout
2. in fact all output *appears* to be sent to stderr as I have yet to see any output at all sent to stdout

**Comment by ARolek** [comment]
This will require reworking how we're handling logging in tegola. Currently we're mainly using `log.Println(...)` which defaults to `os.Stderr`. I'm in favor of cleaning this up and making log levels configurable. @goinggo has an article on this topic we can use for inspiration: [Using The Log Package In Go](https://www.goinggo.net/2013/11/using-log-package-in-go.html) which was turned into the [tracelog](https://github.com/goinggo/tracelog) package.

**Comment by gdey** [comment]
We need to redo our logging output.
For this issue.

1. Vendor in the [tracelog](https://github.com/goinggo/tracelog) package.
2. Added loggers for:
- [ ] Trace
- [ ] Info
- [ ] Error
- [ ] Warning
3. Update log statements to the appropriate logger.

**Comment by ARolek** [comment]
**Logger Proxy API**
- `log.Fatal(string, vals... interface{})` -
  - prevents the program from continuing
  - i.e. can't allocate additional memory
- `log.Error(string, vals... interface{})`
  - non-fatal, but prevents valid execution
  - i.e. can't connect to a database, complete a function call, open file, invalid format
- `log.Warn(string, vals... interface{})`
  - looks unusual, but does not clearly prevent execution
- `log.Info(string, vals... interface{})`
  - i.e. server request logs
- `log.Debug(string, vals... interface{})`
  - high level info for a developer. more than what a sysadmin would typically want
- `log.Trace(string, vals... interface{})`
  - excruciating detail. first cut will try to non compile the statements out. if we find we're still dealing with performance issues, then we will explore turning `log.Trace(...)` into a noop.

**Aux Functions**

Default Log Level is Info.
- SetLogLevel(log.Level)

```go
// tegola/internal/log
package log

var (
   lock syc.Mutex
  // in order 
  IsError bool
  IsWarn bool
  IsInfo bool
  IsDebug bool
  IsTrace bool
)
/* example usage
if log.IsDebug {

}
*/

```
**Logger requirements**
- [ ] if a log is called that is above the set log level, then the function should not do work (just return)
- [ ] log level should be set via the config file
- [ ] log level should be set via an ENV var
- [ ] by default all output in the `log` package should write to `stderr`

**Log output**
- [ ] prefix all statements with timestamp, log level, caller filename and line number.
```
timestamp•LOG_LEVEL•filename.go•linenumber•output
```

**Comment by JivanAmara** [comment]
New logger added with https://github.com/terranodo/tegola/pull/205.
