### ISSUE TITLE
scroll bars showing in viewer

### ISSUE THREAD

**Issue by antoniolocandro** [terranodo/tegola#148]
For some reason scrollbars are showing in firefox and chrome in win10
![tegola_initial_faa](https://user-images.githubusercontent.com/4627073/30767782-2e8b5f00-9fbd-11e7-85b6-2244ae0310d5.png)

**Comment by ARolek** [comment]
@antoniolocandro I'm not able to hide the scroll bars entirely as that's handled by the OS unless I want to implement javascript scrolling. I was able to get rid of the stacked scroll bars though. This is fixed in the v0.4.0 branch and will be part of the beta release. 

Thanks for the report!
