### ISSUE TITLE
Implement Postgres database driver

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#15]
I have used [pgx](https://github.com/jackc/pgx) with PostGIS and it works great.

**Comment by gdey** [comment]
The data provider interface will be the following:

```
InitiProvider — map[string]interface{} -- layers -> sql , name, map[string]interface{} config --> provider, error.
```

```
getLayer(tile, layer_name) --> mvt.Layer, error

```

**Comment by gdey** [comment]
The layer config will use text.Template for the layer name and bbox name. So, the token will be {{.layer}} and {{.bbox}}

**Comment by ARolek** [comment]
@gdey it's going to be important for us to consider resolution when fetching data from PostGIS. Take a look at this ZRES method that leverages the `ST_Simplify` function of PostGIS [here](https://github.com/mapbox/postgis-vt-util). We can probably implement this in code to avoid requiring the PostGIS funcs be installed.

**Comment by jj0hns0n** [comment]
can this be closed now?

**Comment by ARolek** [comment]
@gdey it's not feature complete, but it works. I would say this ticket is not ready to be closed. I need to talk with @gdey about a few things now that we have an end to end implementation.

**Comment by jj0hns0n** [comment]
works for me, thanks for clarification.

**Comment by gdey** [comment]
Change Providers to be a registration based system. 

```go
Provider.Register( name string, initFunc func(map[string]interface{})(tegola.Provider, error)) error // The error will happen if the name is already registered. I think this should be a panic
Provider.Drivers()[]string // Returns a list of drivers that have been register
Provider.For(name string, config map[string]interface{})(tegola.Provider,error)
```

Each provider will need to register by call `Provider.Register()` in it's `init()` function.

The code will include the providers using an _ import.

The `InitFunc` needs to validate the the config; returning and error if it is not correct.

We will, also, change the interface for a tegola.Provider to the following:

```go
type Provider interface{
   MVTLayer(queryName string, layerName string) (mvt.Layer, error)
}
```

The provider config will have the following known fields:

*queries* : This field will be map of name queries.

**Comment by gdey** [comment]
Completed on new_provider_interface branch.
