### ISSUE TITLE
add --version cmdline arg

### ISSUE THREAD

**Issue by sacontreras** [terranodo/tegola#152]
if "--version" is the only arg, tegola should output to stdout and then terminate process
if not, start tegola as usual but add addl. stdout line outputting version (in addition to current stdout output)

**Comment by ARolek** [comment]
@sacontreras I forgot this is not documented yet but we do have support for it on the v0.4.0 builds. Run `tegola -v` or `tegola --version` to have the version output.

**Comment by sacontreras** [comment]
Not yet.  I had to put this one on the backburner to jump on dg-services
tegola devops stuff.

**Comment by sacontreras** [comment]
Oh I misread this initially.  It IS supported already.  Cool.
