### ISSUE TITLE
Add GeoPackage as a Provider

### ISSUE THREAD

**Issue by fawick** [terranodo/tegola#161]
(Somewhat related to #115 and #160)

I wonder whether it would be of interest for tegola to have a `mvt.Provider` for the GeoPackage format. To my knowledge, there is no GeoPackage library for Go, yet. But since it is an open standard maybe  the time is right to kick off one under the tegola roof.

**Comment by jj0hns0n** [comment]
This one is in progress. @jivanamara can you give us an update?

**Comment by JivanAmara** [comment]
Using go-sqlite, I'm writing a basic library to read gpkg files (and the wkbgeometry format used inside them) as a tegola provider.  Have a rough version working on a particular gpkg that loads layers and doesn't throw any errors, but something is preventing tiles from showing up in the map.  Once the branch is working at a basic level and I've cleaned up a bit I'll share.

**Comment by ARolek** [comment]
@fawick a bit more about this. Since Geopackage uses SQLite, we're waiting for an SQLite port to Go. In the mean time a bridge via cgo is necessary. There are two projects working on SQLite in pure go though, and we're watching those.

**Comment by fawick** [comment]
Although I am well aware of the call overhead that CGO induces I would like to make a case for using the official SQLite library via CGO. The main advantage I see is that [the official SQLite sources are rigorously tested](https://www.sqlite.org/testing.html). 

In fact, [their testing suite suffices the very strict requirements of the DO-178 aviation standard for safety-critical software](https://www.sqlite.org/th3.html). As every aviation software creator is required by DO-178 to present and re-do these tests the folks behind SQLite sell this testing suite via a proprietary license. Nevertheless, any SQLite version they make is checked against it behind the curtains before it is released. It is mingboggingly to see such a thing in open-source (and even Public Domain) software and IMHO makes SQLite one of the (if not _THE_) most mature FOSS projects there are.

I reckon they put tens of man years of engineering into coming to that point. Any attempt to come up with a SQLite package in pure Go will be having a hard time ensuring that same level of robustness.

**Comment by ARolek** [comment]
@fawick using CGO is the current strategy that @JivanAmara is working on for several of the reasons you have mentioned and the fact that it's the only way to leverage SQLite in Go. The pure Go projects we're watching:

- [c2go](https://github.com/elliotchance/c2go) - If you take a look at their roadmap, the ultimate goal is to transpile SQLite3.
- [sqlite](https://github.com/cznic/sqlite) - this is another transpiler project with a different approach. 

Ultimately this is a data provider and it needs to be stable. I would prefer tegola be pure Go, but we're going to implement some cgo while other packages mature.

**Comment by JivanAmara** [comment]
- [x ] Add support for "fields" config param
- [ ] Add support for "sql" config param
- [ ] Rewrite tests without testify
