### ISSUE TITLE
504 returned when attempting to retrieve a tile at negative zoom

### ISSUE THREAD

**Issue by jamesyarrington** [terranodo/tegola#163]
**To Reproduce:**
Send a GET to:
```
osm.tegola.io/maps/osm/-1/0/0.pbf
```
**Expected Response:**
A `400 Bad Request`should be returned, along with a message stating that negative zoom levels are not allowed.

**Actual Response:**
A `504 Gateway Time-out` is returned, with no other message.

**Comment by ARolek** [comment]
@jamesyarrington thanks for the report.

**Comment by ARolek** [comment]
Fixed in v0.4.0 will be in the final version release.
