### ISSUE TITLE
Make db connection pool configurable

### ISSUE THREAD

**Issue by gsoyka** [terranodo/tegola#174]
Currently, each worker has a hardcoded limit of 100 database connections in the pool.  For some environments, this results in exceeding the number of allowed connections to the database.  For PaaS environments and the like, it would be helpful to configure a lower limit.

**Comment by ARolek** [comment]
@gsoyka great issue. I will add it to the upcoming version. Thanks for the report.

**Comment by ARolek** [comment]
@gsoyka looks like this is already configurable via the `max_connection` param for the `postgis` provider. @jj0hns0n is running some tests bit you should be good to go.

**Comment by jj0hns0n** [comment]
looks like alex fixed a bug and `max_connections` now works.

**Comment by ARolek** [comment]
looks like there was an error parsing the data type (int64 v int) I have a fix coming. I have also adjusted the language to `max_connections` (plural).
