### ISSUE TITLE
Find home for 2nd WKBGeometry implementation.

### ISSUE THREAD

**Issue by JivanAmara** [terranodo/tegola#185]
Should we make use of this for testing the existing wkb package or just dump it?

**Comment by ARolek** [comment]
@JivanAmara the WKB implementation is currently being updated by @gdey and will be using the new [geom](https://github.com/go-spatial/geom) package we have been working on. I think we should dump this one for now since the type strategy is also being updated.

**Comment by JivanAmara** [comment]
Removed in commit 8fae61cb.
