### ISSUE TITLE
Connection pooling for GPKGProvider

### ISSUE THREAD

**Issue by JivanAmara** [terranodo/tegola#192]

**Comment by gdey** [comment]
Please, wait for the issue to be reviewed and merged into the release branch. Also, if there is a good reason to the close the issue (i.e., because the issue is invalid, or it's not going to be fixed. Add a comment stating the reason for the closing the issue — and the appropriate tags.)

**Comment by JivanAmara** [comment]
As part of a feature branch, closing this as completed on the feature branch.
