### ISSUE TITLE
Factor out hostName() changes into PR on v0.5.0

### ISSUE THREAD

**Issue by JivanAmara** [terranodo/tegola#199]
hostName() only returns the host name, but is used to construct the portions of URLs which include both host and port.  Updates to return a host:port value have been made on issue-161_geopackage_provider.  

Additional changes were made to allow the "port" attribute in a tegola config to be expressed as ":<port>" (current) or as simply "<port>" (new).

Isolate these changes and create PR for them.

**Comment by gdey** [comment]
Please, wait for the issue to be reviewed and merged into the release branch. Also, if there is a good reason to the close the issue (i.e., because the issue is invalid, or it's not going to be fixed. Add a comment stating the reason for the closing the issue — and the appropriate tags.)

**Comment by JivanAmara** [comment]
Merged
https://github.com/terranodo/tegola/pull/212
