### ISSUE TITLE
Windows: error creating connection pool (postgis)

### ISSUE THREAD

**Issue by PetersonGIS** [terranodo/tegola#200]
Running v0.4.2. tegola_windows_amd64.exe results in the following error:

`main.go:54: Failed while creating connection pool: dial tcp :5432: connectex: The requested address is not valid in its context.`

**Comment by ARolek** [comment]
This appears to be an issue with the Go compiler for windows as documented [here](https://github.com/golang/go/issues/22811). Compiling with go 1.9.2 fixes the problem. The task here is to update our CI build tools to use go 1.9.2

**Comment by ARolek** [comment]
Looks like we can add a `deploy` condition to sniff for the appropriate go version as shown in the example [here](https://docs.travis-ci.com/user/languages/go/#Environment-Variable)
