### ISSUE TITLE
Geometry Collection rendering 

### ISSUE THREAD

**Issue by CodeKunal** [terranodo/tegola#204]
Are there any plans on supporting rendering of GeometryCollections? As of now it does not support geometry collections. Correct me if I am wrong.

**Comment by ARolek** [comment]
@CodeKunai currently the MVT Specification does not support rendering geometry collections so tegola has no intent to support them unless the spec changes. [Here are the geometry types](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/README.md#434-geometry-types) the MVT spec currently supports.

There is a work arounds you can consider. Check out the PostGIS function [`ST_CollectionExtract`](https://postgis.net/docs/ST_CollectionExtract.html). You could then create three provider layers, one for each type extracted from the Geometry Collection. You would then be able to style points, line strings and polygons independently.

**Comment by ARolek** [comment]
I'm going to close this now as we don't have plans to fix this unless the MVT spec introduces support for it.
