### ISSUE TITLE
Support environment variables in config file

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#210]
Several issues (#95, #133, #137) are requesting environment variable "injecting" into the config file. For example:

```
[[providers]]
name = "ne"
type = "postgis"
host = "{{.HOST}}"
port = {{.PORT}}
database = "{{.DATABASE}}"
user = "{{.USER}}"
password = "{{.PASSWORD}}"
```

We can accomplish this by using the go text/template package and reading in all the environment variables via os.Env().

**Comment by ARolek** [comment]
An alternative approach is to implement the [toml.TextUnmarshller](https://godoc.org/github.com/BurntSushi/toml#TextUnmarshaler) interface for all our types to sniff for a prefix (i.e. the typical environment var $). This would avoid needing to use the Go template syntax and allow us to use a syntax that is more common place. For example:

```
[[providers]]
name = "ne"
type = "postgis"
host = "$HOST"
port = $PORT
database = "$DATABASE"
user = "$USER"
password = "$PASSWORD"
```

**Comment by JivanAmara** [comment]
I like making the syntax match commonplace usage, why not simply make the replacements before the config goes to toml decoding?

**Comment by ARolek** [comment]
@JivanAmara I'm already playing with a couple ideas, but I think the TextUnmarhshller interface is going to work well. We could read the config file prior to toml processing but I think we're going to shift the problem to regex processing, which is not necessarily a bad thing. Did you have another idea?

**Comment by erictheise** [comment]
I mentioned leveraging the [Foreman](http://blog.daviddollar.org/2011/05/06/introducing-foreman.html) approach in https://github.com/terranodo/tegola-osm/issues/25. Three Go ports are listed in [Foreman's README.md](https://github.com/ddollar/foreman#ports).

Curious to hear @mojodna's latest thinking, too.

**Comment by JivanAmara** [comment]
@ARolek I was thinking using regex processing to search & replace the environment vars in the config text (i.e. "port = $PORT" -> "port = 8080", then hand it off for decoding.  What do you mean by shifting the problem to regex processing?

**Comment by JivanAmara** [comment]
@ARolek Something like this: https://github.com/terranodo/tegola/tree/issue-210_config_env_vars

**Comment by ARolek** [comment]
@JivanAmara I dig the approach. I added a few comments, but overall I think this will work.
