### ISSUE TITLE
wkb.Collection not a tegola.Collection

### ISSUE THREAD

**Issue by remster** [terranodo/tegola#226]
airmap/gis/tile/mb/server/test/utils.go:143:7: cannot use collection (type *wkb.Collection) as type tegola.Collection in assignment:
	*wkb.Collection does not implement tegola.Collection (missing Geometries method)

**Comment by gdey** [comment]
The new geom/encoding/wkb package uses geom/geometries. Those geometries fully support collections. This is available in the v0.6.0 branch.
