### ISSUE TITLE
A GET request for a Tile with a negative row value is successful

### ISSUE THREAD

**Issue by jamesyarrington** [terranodo/tegola#229]
**To Reproduce:**
Send this GET Request:
```
<Tegola URL>/maps/osm/10/0/-1.pbf
```

**Expected Response:**
The server should return `400 Bad Request`.

**Actual Response:**
The Server returns `200 OK`.
This is the Tile object (converted using pbf, vector-tile):
```
VectorTile {
      layers:
       { 'debug-tile-outline':
          VectorTileLayer {
            version: 2,
            name: 'debug-tile-outline',
            extent: 4096,
            length: 1,
            _pbf: [Object],
            _keys: [Array],
            _values: [Array],
            _features: [Array] },
         'debug-tile-center':
          VectorTileLayer {
            version: 2,
            name: 'debug-tile-center',
            extent: 4096,
            length: 1,
            _pbf: [Object],
            _keys: [Array],
            _values: [Array],
            _features: [Array] } } }
```

_I do not know if the `debug-tile-outline` and `debug-tile-center` are from the vector-tile converter package, or from Tegola._

**Comment by gdey** [comment]
The debug-tile-outline and debug-tile-center are added by Tegola. When you pass `?debug` to the inspector, a center point and the outline is drawn. These are the layers for those geometries.
