### ISSUE TITLE
Provider/postgis: Using !ZOOM! token can cause nil geom type on style generation

### ISSUE THREAD

**Issue by PetersonGIS** [terranodo/tegola#232]
Using the min_zoom field in ne_110m_land as a filter in the config toml like this:

`sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, min_zoom FROM ne_110m_land WHERE min_zoom < !ZOOM! and wkb_geometry && !BBOX!"`

can cause this error:
![error](https://user-images.githubusercontent.com/5266205/34125403-6135e464-e3f3-11e7-8bc8-233198242b40.PNG)

**Comment by ARolek** [comment]
The way this works right now is tegola sniffs for `ST_AsBinary` and replaces it with `ST_GeometryType`. This is not super stable as we have plans for removing the requirement of wrapping geometry types with `ST_AsBinary` #180. Unfortunately without running the query we can't know what the geometry type is as the user provided SQL may change the resulting geometry type.

That considered, the main problem right now is if the provided SQL filters out all features via a WHERE clause (i.e. !ZOOM! token). One solution is to sniff for `WHERE` and drop everything from the start of the where clause to the end of the statement and then add `LIMIT 1`. This would return a single record form the query so we would know the output geometry and we would always get a record.

**Comment by ARolek** [comment]
Another detail to note about this strategy, we're currently doing a string.ToLower() on the SQL so we can match the two `ST_*` methods, but this may malform the SQL when case is important (i.e. WHERE property = 'SOME_VAL')

**Comment by ARolek** [comment]
Final strategy turned out to be replacing the `!ZOOM!` token with `ANY('{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24}')` which basically turns off the zoom filtering for this situation but keeps the SQL intact.
