### ISSUE TITLE
How do we want to handle CORS?

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#28]
CORS should probably be configurable. Let's use this issue to decide if we want a default of: "Access-Control-Allow-Origin":"*" and if not how much of CORS do we want to make configurable?

**Comment by lukasmartinelli** [comment]
> CORS should probably be configurable. Let's use this issue to decide if we want a default of: "Access-Control-Allow-Origin":"*" and if not how much of CORS do we want to make configurable?

Trying to integrate #83.
CORS currently does not work for tiles specified in http://tegola.cfapps.io/capabilities/bonn_osm.json

![maputnik](https://cloud.githubusercontent.com/assets/1288339/19084378/a0ea4434-8a66-11e6-878d-87c4246cc9ec.png)

**Comment by ARolek** [comment]
I think what's going on is the OPTIONS preflight needs to be implemented for the `/capabiliites` and `/capabiliites/map_name.json` endpoints. Fix coming right up.

**Comment by ARolek** [comment]
@lukasmartinelli we have pushed an update to the server at  http://tegola.cfapps.io/capabilities/bonn_osm.json. Let me know if you ht any other issues.
