### ISSUE TITLE
binary linked in docs is way too old

### ISSUE THREAD

**Issue by george-silva** [terranodo/tegola#284]
Hello everyone.

The linux binary (probably the other platforms as well) is really outdated. I followed the procedure documented and it did not worked.
Then I checked the version and downloaded the newer version, which worked fine.

Let's change it, otherwise some people might give up on their first try.

**Comment by ARolek** [comment]
@george-silva thanks for the heads up. I will get that fixed up on the docs. We're also working on updating the docs after we cut v0.6.0.

**Comment by ARolek** [comment]
@george-silva this is now fixed.
