### ISSUE TITLE
vendor external dependencies

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#29]
The goal is to keep project dependencies at a minimum. Any necessary external dependencies need to be included in the the projects `vendor/' folder.

**Comment by gdey** [comment]
@ARolek which dependency manager were you thinking of using again?

**Comment by ARolek** [comment]
@gdey [govendor](https://github.com/kardianos/govendor). I have already implemented it on the issue-13 branch I'm working on so once I merge that in you will see the new vendor folder.
