### ISSUE TITLE
 handle_map_style.go:138: layer (providerLayerName: landuse_areas_gen0) has unsupported geometry type (<nil>)

### ISSUE THREAD

**Issue by vchrisb** [terranodo/tegola#302]
I'm trying to deploy tegola.
I did try the "Getting Started" as well as the "tegola-osm" variant, but in both cases I do get an error like this:
```
handle_map_style.go:138: layer (providerLayerName: landuse_areas_gen0) has unsupported geometry type (<nil>)
handle_map_style.go:138: layer (providerLayerName: water_areas_gen0) has unsupported geometry type (<nil>)
```

I also tried `v0.6.0` as I've seen there should be some better `nil` handling just in the latest commits.

I also made sure, that my database user is owner on every table.

Any idea where this error comes from?

Thx.

**Comment by ARolek** [comment]
@vchrisb can you paste in the SQL for those specific layers?

**Comment by vchrisb** [comment]
@ARolek these are the lines in the tegola-osm repo:
https://github.com/terranodo/tegola-osm/blob/master/tegola.toml#L98
https://github.com/terranodo/tegola-osm/blob/master/tegola.toml#L43

for the getting started example it was for all three layers in http://tegola.io/getting-started/
Though for the getting-started I didn't check the table owner.

**Comment by ARolek** [comment]
@vchrisb I just recreated the issue. So what's going on is the condition `AND area > 1000000000` is filtering out all the records so tegola is not able to understand what the geometry type is for that layer. you can change the filter for the area to `AND area > 10000` and it should work. This is not a great solution though so I think I'm going to need to figure out a strategy for auto generating a style when tegola can't read the geometry type.

I do see a bug though which is causing the style to break when we don't know the geom type. I can put a fix in on the v0.6.0 branch to address this soon.  Another possible solution is use the line style when tegola can't read the geometry type. Let me do some testing but I think I can have a fix available shortly. 

Thanks for the report.

**Comment by ARolek** [comment]
@vchrisb I just pushed up a fix to the v0.6.0 branch if you want to give it a test. If we can't generate a style we don't, rather than break the interface.

**Comment by vchrisb** [comment]
thx, I'll give it a try!

**Comment by ARolek** [comment]
@vchrisb have you had a chance to try this on your end? we're going to be cutting the v0.6.0 branch soon so hopefully this is cleaned up for you.

**Comment by vchrisb** [comment]
@ARolek thx, it did work.
