### ISSUE TITLE
version flag doesn't show version

### ISSUE THREAD

**Issue by angusscown** [terranodo/tegola#317]
tegola version 

➜  tegola git:(v0.6.0) ./tegola version
version not set

I'm new to go so *think* I built the v0.6.0 branch as I need the non debug tiles resolved.  Trying to work out how I know the binary is the right version.  It is 'different' when I switch branches (diff).

**Comment by ARolek** [comment]
@angusscown the version flag is populated at build time by injecting a value into the main.Version var. For local testing you could do something like:

`go build -ldflags "-w -X github.com/terranodo/tegola/cmd/tegola/cmd.Version=$(git rev-parse --short HEAD)"`

That will use the shot version of the current git hash as the version tag.
