### ISSUE TITLE
PostGIS support for geometry collections

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#33]
The issue with Geometry collections is they only have one `gid`. This could be an issue when encoding to an MVT tile. If so, we should we dynamically create unique ids for each feature in the geometry collection? 

As of now, the geometry collection will not be handled.

**Comment by jj0hns0n** [comment]
Lets research how MapBox handles this. Geometry Collections are going to be necessary.

**Comment by ARolek** [comment]
@jj0hns0n that's the plan. We just need to figure out how to best handle the collections. The featureID is critical for associating a feature across tiles. With a geometry collection there is a single id for several features. This may be fine, or we may need to generate ids on the fly.

**Comment by gdey** [comment]
Also, to note the mapbox spec does not support geometry collections for the encoding:

https://github.com/mapbox/vector-tile-spec/blob/master/2.1/README.md#434-geometry-types

>  Geometry collections are not supported.

**Comment by ARolek** [comment]
this is not currently supported by the MVT format so we're closing this issue for now.

**Comment by CodeKunal** [comment]
So does this mean Tegola MVT does not support Geometry collection as in we won't be able to render geometry collections on the map? As I understand reading through above comments even Mapbox does not render GeometryCollection? Correct me if I am wrong. Thanks
