### ISSUE TITLE
Reveal z/x/y for a tile when debugging

### ISSUE THREAD

**Issue by pnorman** [terranodo/tegola#332]
There should be some way to reveal the z/x/y for a tile when debugging. This should be in a form that the triplet can be copied and pasted so it can looked at with another program.

**Comment by ARolek** [comment]
This can be done by adding `?debug=true` to the viewer's URL or by appending `?debug=true` to the tile requests. A few links for reference: [Client Side Debugging](https://github.com/terranodo/tegola#client-side-debugging), [Debugging](http://tegola.io/debugging/#client-side). 

I will add some additional documentation about how to do this in the viewer, or maybe we should add a button to the viewer to make it even easier. ;-)

**Comment by pnorman** [comment]
> should add a button to the viewer to make it even easier

Yes - although there's probably a better way than editing the vector tiles to do it within the front-end itself.
