### ISSUE TITLE
Unexpected query lowercasing when selecting geometry type

### ISSUE THREAD

**Issue by russss** [terranodo/tegola#336]
When tegola tries to detect the geometry type of a layer, it [lowercases the entire SQL query](https://github.com/terranodo/tegola/blob/7fb74f7a88fd2cfda141297fb4e65e58d71a0f09/provider/postgis/postgis.go#L275). 

This isn't great as it can change the meaning of the query.

**Comment by ARolek** [comment]
@russss thanks for the report. We have fixed this in the v0.6.0 branch which we’re just about to release (finalizing build scripts). If you can build from source it would be great to see if the new branch no longer causes an issue for you.

**Comment by russss** [comment]
Aha thanks, I'll definitely give that a try tomorrow!

**Comment by russss** [comment]
Looks good now, thanks - 0.6.0 also seems to fix some other miscellaneous weirdness I was seeing.

**Comment by ARolek** [comment]
Beautiful! Thanks for trying to build out.
