### ISSUE TITLE
Add query string param for debug toggle (?debug=true)

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#36]

**Comment by gdey** [comment]
Do we want this to be a query string param or a parameter for the program?

**Comment by ARolek** [comment]
@gdey I'm open for either. I just think it would be easy to debug if all you had to do is append the debug flag on the URL instead of restart the server with a new config.

**Comment by gdey** [comment]
How do we send that to the server. Using a cookie? So that the calls for the vector tiles get that?

**Comment by ARolek** [comment]
@gdey I was thinking we could add ?debug=true on the client side init: for example look at this line: https://github.com/terranodo/tegola/blob/master/cmd/tegola/static/open-layers-example.html#L30

**Comment by jj0hns0n** [comment]
+1 on a query string param vs in the config. Easier to use that way.
