### ISSUE TITLE
Support 4326 projection

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#47]
Move SRID from the map to the layer. The SRID should indicate what the underlining srid of the data is for that geometry. We will convert that data WebMercator (3857). If the field is not provided it will be assumed to be in 3857. 

When filling out the bounding box, I need to make sure there is an ST_TRANSFORM done on the created envelope. Transforming from 3857 to the passed in SRID. (4326) in this case. Or make sure the envelope in the correct coordinates.

**Comment by gdey** [comment]
References:
http://www.gal-systems.com/2011/07/convert-coordinates-between-web.html
http://wiki.openstreetmap.org/wiki/Mercator

**Comment by gdey** [comment]
So, playing with this further; I discovered that the srid is in the wrong place. Right now we have it set with the provider, when I think it should go with the table, in the layers area. Each different table can have a different table setting. Also, I don't know if I loaded the data wrong or not, but so far my tests are showing the polygons in the right place.

**Comment by gdey** [comment]
Made some more progress on this with @ARolek help. Branch (37fcc6ee9fdb87bad0744486cb02df56cae2dd8b) issue_47 has what I believe a working implementation. Still need tests.

**Comment by ARolek** [comment]
It appears that only the Y values are off. X seems to be spot on.

**Comment by gdey** [comment]
Okay, my hunch was write. When I did not conversion I used the more accurate but slower `Elliptical (true) Mercator Projection` algo's from http://wiki.openstreetmap.org/wiki/Mercator#C . When I implemented and use the `Spherical Pseudo-Mercator projection`, things line up correctly.

**Comment by gdey** [comment]
All that is left for this ticket is to write some tests, for the math functions. And Document it.
