### ISSUE TITLE
PostGIS config without custom SQL is throwing invalid SQL error

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#66]
When setting up a PostGIS data provider that uses `tablename`, `geometry_fieldname` and `id_fieldname` combo (no custom SQL statement), the following error is being thrown: 

```
2016/08/06 17:27:00 mvt layer error ERROR: syntax error at or near "," (SQLSTATE 42601)
```

It looks like an extra comma is being added when the SQL is being built by the driver. 

References: 
- [Config File](https://dpaste.de/foF8)
- [Error Log](https://dpaste.de/RhFK)

**Comment by ARolek** [comment]
I was able to recreate this issue, and the problem has to do with with a column name being a keyword. In the following SQL statement, the word "natural" is a [reserved Postgres keyword](https://www.postgresql.org/docs/8.1/static/sql-keywords-appendix.html). 

```sql
SELECT ogc_fid,ST_AsBinary(wkb_geometry) AS wkb_geometry,osm_id,osm_way_id,name,type,aeroway,amenity,admin_level,barrier,boundary,building,craft,geological,historic,land_area,landuse,leisure,man_made,military,natural,office,place,shop,sport,tourism,other_tags
FROM
	public.grassland
WHERE
	wkb_geometry && ST_MakeEnvelope(-1.3039545527409669e+07,3.8573181948461905e+06,-1.3037099542504884e+07,3.8548722099414053e+06,3857)
```

An immediate solution would be to wrap all the field names in quotes

**Comment by gdey** [comment]
That should be pretty easy to do. That is what I was suspecting. Thanks for confirming it for me.

**Comment by kalxas** [comment]
good catch :)

**Comment by kalxas** [comment]
yes, the pgdump was from the OSM database, after processing with osmosis (splitting layers to different tables)
