### ISSUE TITLE
Geometry errors at various zoom levels

### ISSUE THREAD

**Issue by allspatial** [terranodo/tegola#90]
I am getting geometry errors in several polygon and line layers at various zoom levels. The higher the zoom level the more errors appear (screenshot 2). I am using tegola_darwin_amd64 (v 0.3.0) from the release page. I can provide sample data in Shapefile format or as PostgreSQL dump if required.

Many thanks,

Michael

![error](https://cloud.githubusercontent.com/assets/12534211/21543042/025aa2f0-cddc-11e6-9446-29c4cc1e9209.png)

![error2](https://cloud.githubusercontent.com/assets/12534211/21543167/2e25f69a-cddd-11e6-9a7e-9a6296573dea.png)

**Comment by ARolek** [comment]
@allspatial thanks for the report. What client side library are you using? If you're using Mapbox then we have seen this issue and it should be fixed in our 0.4 release which comes with geometry clipping (and is nearing completion!).

If you're using OpenLayers then this is a new issue and your shapefile would be helpful.

**Comment by allspatial** [comment]
Hi @ARolek! Many thanks for your swift reply! I am indeed using mapbox (mapbox-gl-js  v 0.29.0). I wouldn't mind using OpenLayers but I did a few tests about three months back and the performance of OL when labelling thousands of features was significantly lower than with mabbox-gl-js. However, that might have improved meanwhile. I am very much looking forward to your 0.4 release then.

**Comment by allspatial** [comment]
I would be glad to test the pre-release, I really want to use Tegola for quite an important government project. Are there any instructions on how to build the binary (I haven't done anything with Go so far)?

**Comment by ARolek** [comment]
@allspatial I can put together some instructions in the Readme.md for building. Do you have go installed? If so, you can clone the repo, and then navigate to the `cmd/` directory and run the following:

```
go build -o tegola *.go
./tegola --config=path/to/config.toml
```

For additional details on the config file check out our [docs](http://tegola.io/configuration/).

**Comment by allspatial** [comment]
I installed Go via Homebrew. Building the tegola binary went smoothly. I had to cd to **cmd/tegola** though, not just **cmd/**. Many thanks!!!

**Comment by ARolek** [comment]
@allspatial good catch. I have added the building instructions to the Readme file [here](https://github.com/terranodo/tegola/blob/master/README.md#building-from-source). We will let you know when clipping is ready for you to test.

**Comment by allspatial** [comment]
@ARolek, perfect. I am looking forward to that. Many thanks again!

**Comment by gdey** [comment]
Moving this to #56; as I believe these errors are related to clipping. (As pointed out by @allspatial )
