### ISSUE TITLE
Tegola seems to ignore the config Port tag

### ISSUE THREAD

**Issue by andreschardong** [terranodo/tegola#91]
Tegola seems to ignore the config Port tag. 
On my config.toml it is set to :9090, however the server is always started on 8080.
I'm using 0.30 windows x64

**Comment by ARolek** [comment]
@andreschardong thanks for the report. This has been fixed in master and is due to be released with the upcoming 0.4 release. If you want, I can put together a build of master for Windows for you to test.

**Comment by andreschardong** [comment]
Thank you for the quick reply. No worries! I will wait for the 0.4 release.

**Comment by andreschardong** [comment]
Just build it following the instructions and the trunk version accepts the port set on config file. Thanks!
