### ISSUE TITLE
parallelisation to use cores?

### ISSUE THREAD

**Issue by shongololo** [terranodo/tegola#98]
Does terranodo scale to use multiple cores if available? 

Or is it necessary to run multiple individual apps to utilise all cores? e.g. as would be the case with Gunicorn in front of multiple python apps?

**Comment by ARolek** [comment]
Short answer: Yes.

A bit of an explanation. We compile with Go 1.7+ which by default uses `GOMAXPROC = runtime.NumCPU`. This change happened in Go 1.5 ([reference](https://docs.google.com/document/d/1At2Ls5_fhJQ59kDK2DFVhFu3g5mATSXqqV5QrxinasI/edit)). For each incoming request tegola spins up a go routine which is the default behavior for  `net/http` requests. Additionally we spin up a go routine for each layer being fetched from a data provider. If you're interested in the thread you can check out issue #68 which also has a reference to the commit.

**Comment by shongololo** [comment]
Thank you for the explanation.
